[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pytest>=8.3.5"]

[dependency-groups]
dev = ["pytest-cov>=6.1.1"]

[tool.pytest.ini_options]
addopts = "--cov=. --cov-report=term-missing --cov-report=html"
testpaths = ["linked_list"]                                     # 指定测试目录

[tool.coverage.run]
omit = ["main.py"] # 忽略无需覆盖的文件
